# .streamlit/secrets.toml

# 這裡填入您剛剛複製的 Google Drive 資料夾 ID
gdrive_folder_id = "您的_FOLDER_ID_貼在這裡"

[gcp_service_account]
# 打開剛剛下載的 json 檔，把裡面的內容依照下面格式貼上
type = "service_account"
project_id = "您的project_id"
private_key_id = "您的private_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\n您的超長金鑰\n-----END PRIVATE KEY-----\n"
client_email = "您的機器人email"
client_id = "..."
auth_uri = "..."
token_uri = "..."
auth_provider_x509_cert_url = "..."
client_x509_cert_url = "..."
